# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'ipaddr'

# Define some globals
# Master IP, ( slaves are allocated by incrementing from this base ip)
MASTER_IP   = "172.16.1.201"
SLAVE_COUNT = 2


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"     # NOTE TESTED WORKING WITH version '20180621.0.0'.

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.define "master", primary: true do |master|
    master.vm.hostname = "kmaster"
    master.vm.network "public_network", ip: MASTER_IP
    master.vm.network "forwarded_port", host: 8001, guest: 8001, guest_ip: "127.0.0.1", host_ip: "127.0.0.1" # forwarding 8001 for Kubernetes dashboard
    master.vm.provision "shell", inline: <<-SHELL
      /vagrant/provision-master.bash --master #{MASTER_IP} --host #{MASTER_IP}
    SHELL
  end


  ip_addr = IPAddr.new MASTER_IP

  (1..SLAVE_COUNT).each do |i|
    config.vm.define "slave#{i}" do |slave|
      ip_addr = ip_addr.succ
      slave.vm.hostname = "kslave#{i}"
      slave.vm.network "public_network", ip: "#{ip_addr}"
      slave.vm.provision "shell", inline: <<-SHELL
        /vagrant/provision-slave.bash --master #{MASTER_IP} --host #{ip_addr}
      SHELL
    end
  end
end


